In [2]:
import spacy

if spacy.require_gpu():
    print("GPU is available and being used by SpaCy")
else:
    print("GPU is not being used by SpaCy")

2023-05-30 17:51:39.528578: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-30 17:51:40.252528: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-05-30 17:51:41.091694: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-05-30 17:51:41.095693: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-05-30 17:51:41.095727: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_exec

GPU is available and being used by SpaCy


In [3]:
import cupy as cp

# Create a random array on GPU
x_gpu = cp.random.random((1000, 1000))

# Perform some computations on the GPU
y_gpu = cp.sin(x_gpu) + cp.cos(x_gpu)

# Transfer the result back to the CPU
y_cpu = cp.asnumpy(y_gpu)

# Verify the results
print(y_cpu)

[[1.35658795 1.11741288 1.27547725 ... 1.20467084 1.4141815  1.40907389]
 [1.32106028 1.41400743 1.41334304 ... 1.2485858  1.15324436 1.40316303]
 [1.40228054 1.41387887 1.3984469  ... 1.00532433 1.33745478 1.38578192]
 ...
 [1.17033013 1.07725698 1.07254289 ... 1.41343266 1.30680035 1.29697091]
 [1.41275781 1.25629606 1.37270043 ... 1.41315782 1.38805216 1.0529424 ]
 [1.41215084 1.30688538 1.40787725 ... 1.25585193 1.35366125 1.10743965]]
